project:
  type: website

website:
  title: "Travis Hinkelman"
  site-url: "https://www.travishinkelman.com"
  description: "Personal website for Travis Hinkelman"
  navbar:
    right:
      - text: About
        href: pages/about.qmd
      - icon: github
        href: https://github.com/hinkelman
      - icon: envelope
        href: "mailto:thinkelman@pm.me"
      - icon: linkedin
        href: https://www.linkedin.com/in/travis-hinkelman-36604955/
      - icon: rss
        href: index.xml

format:
  html:
    toc: true
    theme:
      - flatly
      - brand
    css: styles.css
    include-in-header: 
      - text: |
          <script data-goatcounter="https://thinkelman.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>

editor: source

