# The URL the site will be built for
base_url = "https://www.travishinkelman.com/"
title = "Travis Hinkelman"
description = "Data Scientist. Ecological Modeler. R Programmer. Scheme Enthusiast."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
taxonomies = [{ name = "tags", feed = true }]
generate_feeds = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
highlight_theme = "css"
highlight_themes_css = [
    { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
    { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here

[extra.feather]
# theme = "light"
# hide_nav_image = false
# opengraph = { image = "" }
# disqus_id = ""
# cusdis_id = ""
social =  { url = "https://bsky.app/profile/thinkelman.bsky.social", display = "@thinkelman.bsky.social" }
# timezone = "America/New_York"

# [extra.feather.analytics]
goatcounter_id = "thinkelman"
