# The URL the site will be built for
base_url = "https://www.travishinkelman.com"

compile_sass = true
title = "Travis Hinkelman"
description = "Data Scientist. Ecological Modeler. R Programmer. Scheme Enthusiast."
generate_feeds = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[markdown]
highlight_code = false

[extra]
author = "Travis Hinkelman"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Travis Hinkelman"
