---
title: chez-stats is now available through Raven
author: Travis Hinkelman
date: '2019-10-19'
slug: chez-stats-now-available-through-raven
categories:
  - ChezScheme
  - chez-stats
  - Raven
tags:
  - libraries
  - packages
  - statistics
---

My little statistics library, [`chez-stats`](https://github.com/hinkelman/chez-stats), is now available for installation through [Raven](http://ravensc.com), a package manager for Chez Scheme. Raven aims to provide an easy-to-use tool for local package management. 

Raven's [installation instructions](https://guenchi.gitbooks.io/raven/content/installation.html) are straightforward. However, on macOS Catalina, I had to use `sudo` when making a copy of the Chez Scheme compiler, i.e., `sudo cp chez scheme`.

When starting a new project, `raven init` will prompt you to provide the content to populate a `package.sc`^[If you add `*.sc linguist-language=Scheme` in `.gitattributes` for a repository, then GitHub will associate your `.sc` files as Scheme, not Scala, files.] file with the metadata for your project. `raven init` also creates a `lib` folder for housing the packages you install in your project with `raven install PACKAGENAME`. It is not necessary to run `raven init` first. `raven install PACKAGENAME` will also create a `lib` folder and `package.sc` file that you can then edit with your favorite text editor.

`chez-stats` itself has no dependencies, but the tests depend on the `srfi` package ([`srfi 64`](https://srfi.schemers.org/srfi-64/srfi-64.html)) and `chez-stats`. Thus, the test folder is a separate project within the `chez-stats` repository with its own `package.sc` file.^[At the time of this writing, Raven hadn't yet picked up the version of `chez-stats` that uses this file structure, but it is available in the [`chez-stats` repo](https://github.com/hinkelman/chez-stats) on GitHub.] From within the tests folder, you can run `raven install`, which will read `package.sc` and create the `lib` folder with the dependencies installed. Then `raven run tests.ss` will run the tests.^[Alternatively, you could run the tests with `chez tests.ss --libdirs "./lib:"`.]

I've only covered basic Raven functionality. See the [documentation](https://guenchi.gitbooks.io/raven/content/) to learn about the full capabilities.
