---
title: Exploring Scheme implementations
author: Travis Hinkelman
date: '2019-07-28'
slug: exploring-scheme-implementations
categories:
  - Racket
  - Chicken
  - ChezScheme
tags: []
draft: false
---

Over the last 6 months, I have been learning [Racket](https://racket-lang.org) in my free time. One of my [first posts on this blog](/post/programming-horizons/) laid out my reasons for choosing Racket. The relatively low barrier to entry (e.g., easy installation of Racket and packages, DrRacket IDE, good docs, etc.) allowed me to build momentum with Racket and I was feeling satisfied with my choice of Racket as an [alternative to Python](https://dustycloud.org/blog/racket-is-an-acceptable-python/).

My enthusiasm for Racket led me to spend most of a recent weekend watching a livestream of [RacketCon](https://con.racket-lang.org). In the 'State of Racket' talk, Matthew Flatt proposed that it is time to start moving forward with the development of Racket2^[Racket2 is a placeholder name for a language that would evolve from Racket and include breaking changes.] and made a few suggestions, including changing the surface syntax to use infix notation. The proposed change to the surface syntax kicked up quite a duststorm on the Racket mailing list (e.g., [here](https://groups.google.com/d/msg/racket-users/HiC7z3A5O-k/XPR2wbSJCQAJ), [here](https://groups.google.com/d/msg/racket-users/ewWuCvbe93k/e-tMWwlVAwAJ), and [here](https://groups.google.com/d/msg/racket-users/vN_1uUJZnXo/5bXiMEBvCgAJ)) and trickled over to [Twitter](https://twitter.com/lexi_lambda/status/1152171606648786945).

I had a surprisingly strong reaction to the proposed changes to Racket and eventually realized that I have come to love Scheme syntax. I find that it fits my brain and I expect it to make me a more productive programmer. A *potential* move away from Scheme syntax in Racket2 would not preclude me from continuining to use #lang Racket as part of the Racket ecosystem; a point made frequently by the Racket core developers. I don't doubt their earnestness, but, even the possibility that Racket might become a 2nd-class citizen in its own ecosystem one day considerably dampens my enthusiasm for learning Racket. Moreover, this whole discussion has reinforced my lingering concern that the emphasis on programming language research might not make Racket the best choice for a general-purpose programming language.^[Alternatively, I'm looking for other ways to rationalize my move away from Racket.]

>While these research problems may not be forefront on the minds of all Racket users, keep in mind that Racket exists because of research and remains supported almost entirely by research. -Matthew Flatt

Thus, over the last couple of weeks, I've been reading about Scheme implementations to choose an alternative to Racket. The two resources that I found most useful were [Awesome Scheme](https://github.com/schemedoc/awesome-scheme) and a blog post on [Scheme for scientific computing](http://fmnt.info/blog/20181029_scheme.html). I initially narrowed my choice down to [Chicken Scheme](https://www.call-cc.org) and [Chez Scheme](https://cisco.github.io/ChezScheme/).

Chicken is an obvious choice for me given that it is beginner friendly with a good community. The tagline describes Chicken as "a practical and portable Scheme," which is appealing as a general-purpose programming language. Chicken has a relatively large package ecosystem and an easy-to-use package installer. The main drawback right now is that a seemingly large number of packages (called eggs) have not yet been ported to Chicken 5, which was released less than a year ago and included breaking changes to package management.

Chez Scheme has only been available as an open-source language since 2016. The package ecosystem lags behind other prominent Scheme implementations. However, Chez has a reputation as being solidly engineered and blazingly fast. Chez has a great REPL that is a joy to use. Moreover, it is based on the Revised<sup>6</sup> Report on Scheme (R6RS) and philosophically aligned with Racket.^[Chicken is based on R5RS.]

As of today, I'm moving forward with learning Chez Scheme. If Racket moves toward non-Scheme syntax, there could be considerable opportunities for Chez to grow its community. My gut feeling is that jumping on the Chez bandwagon now could pay off nicely in a few years. I'm in no hurry to put Chez to work for me, though. I have time to learn and grow with the community.

